{% set version = "1.2.3" %}

package:
    name: widgetsnbextension
    version: "1.2.3"

source:
    fn: widgetsnbextension-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-{{ version }}.tar.gz
    md5: 96b4adc12e70de9c54b5eb103e1167c8

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - notebook >=4.2.0
    run:
        - python
        - notebook >=4.2.0

test:
    imports:
        - widgetsnbextension

about:
    home: http://ipython.org
    license: BSD 3-clause
    summary: IPython HTML widgets for Jupyter

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
